{"name": "test_invalid_login", "status": "failed", "statusDetails": {"message": "Failed: Error during invalid login or pop-up not found: Message: \nStacktrace:\n0   chromedriver                        0x0000000104e2aa54 cxxbridge1$str$ptr + 2803960\n1   chromedriver                        0x0000000104e22cf0 cxxbridge1$str$ptr + 2771860\n2   chromedriver                        0x000000010496e864 cxxbridge1$string$len + 93028\n3   chromedriver                        0x00000001049b5410 cxxbridge1$string$len + 382736\n4   chromedriver                        0x00000001049f6480 cxxbridge1$string$len + 649088\n5   chromedriver                        0x00000001049a97ec cxxbridge1$string$len + 334572\n6   chromedriver                        0x0000000104defccc cxxbridge1$str$ptr + 2562928\n7   chromedriver                        0x0000000104df2f98 cxxbridge1$str$ptr + 2575932\n8   chromedriver                        0x0000000104dd02c4 cxxbridge1$str$ptr + 2433384\n9   chromedriver                        0x0000000104df3810 cxxbridge1$str$ptr + 2578100\n10  chromedriver                        0x0000000104dc12f0 cxxbridge1$str$ptr + 2371988\n11  chromedriver                        0x0000000104e1357c cxxbridge1$str$ptr + 2708512\n12  chromedriver                        0x0000000104e13708 cxxbridge1$str$ptr + 2708908\n13  chromedriver                        0x0000000104e2293c cxxbridge1$str$ptr + 2770912\n14  libsystem_pthread.dylib             0x00000001905282e4 _pthread_start + 136\n15  libsystem_pthread.dylib             0x00000001905230fc thread_start + 8", "trace": "tests/test_login_page.py:53: in test_invalid_login\n    WebDriverWait(browser, 20).until(\n/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/selenium/webdriver/support/wait.py:146: in until\n    raise TimeoutException(message, screen, stacktrace)\nE   selenium.common.exceptions.TimeoutException: Message: \nE   Stacktrace:\nE   0   chromedriver                        0x0000000104e2aa54 cxxbridge1$str$ptr + 2803960\nE   1   chromedriver                        0x0000000104e22cf0 cxxbridge1$str$ptr + 2771860\nE   2   chromedriver                        0x000000010496e864 cxxbridge1$string$len + 93028\nE   3   chromedriver                        0x00000001049b5410 cxxbridge1$string$len + 382736\nE   4   chromedriver                        0x00000001049f6480 cxxbridge1$string$len + 649088\nE   5   chromedriver                        0x00000001049a97ec cxxbridge1$string$len + 334572\nE   6   chromedriver                        0x0000000104defccc cxxbridge1$str$ptr + 2562928\nE   7   chromedriver                        0x0000000104df2f98 cxxbridge1$str$ptr + 2575932\nE   8   chromedriver                        0x0000000104dd02c4 cxxbridge1$str$ptr + 2433384\nE   9   chromedriver                        0x0000000104df3810 cxxbridge1$str$ptr + 2578100\nE   10  chromedriver                        0x0000000104dc12f0 cxxbridge1$str$ptr + 2371988\nE   11  chromedriver                        0x0000000104e1357c cxxbridge1$str$ptr + 2708512\nE   12  chromedriver                        0x0000000104e13708 cxxbridge1$str$ptr + 2708908\nE   13  chromedriver                        0x0000000104e2293c cxxbridge1$str$ptr + 2770912\nE   14  libsystem_pthread.dylib             0x00000001905282e4 _pthread_start + 136\nE   15  libsystem_pthread.dylib             0x00000001905230fc thread_start + 8\n\nDuring handling of the above exception, another exception occurred:\ntests/test_login_page.py:58: in test_invalid_login\n    pytest.fail(f\"Error during invalid login or pop-up not found: {e}\")\nE   Failed: Error during invalid login or pop-up not found: Message: \nE   Stacktrace:\nE   0   chromedriver                        0x0000000104e2aa54 cxxbridge1$str$ptr + 2803960\nE   1   chromedriver                        0x0000000104e22cf0 cxxbridge1$str$ptr + 2771860\nE   2   chromedriver                        0x000000010496e864 cxxbridge1$string$len + 93028\nE   3   chromedriver                        0x00000001049b5410 cxxbridge1$string$len + 382736\nE   4   chromedriver                        0x00000001049f6480 cxxbridge1$string$len + 649088\nE   5   chromedriver                        0x00000001049a97ec cxxbridge1$string$len + 334572\nE   6   chromedriver                        0x0000000104defccc cxxbridge1$str$ptr + 2562928\nE   7   chromedriver                        0x0000000104df2f98 cxxbridge1$str$ptr + 2575932\nE   8   chromedriver                        0x0000000104dd02c4 cxxbridge1$str$ptr + 2433384\nE   9   chromedriver                        0x0000000104df3810 cxxbridge1$str$ptr + 2578100\nE   10  chromedriver                        0x0000000104dc12f0 cxxbridge1$str$ptr + 2371988\nE   11  chromedriver                        0x0000000104e1357c cxxbridge1$str$ptr + 2708512\nE   12  chromedriver                        0x0000000104e13708 cxxbridge1$str$ptr + 2708908\nE   13  chromedriver                        0x0000000104e2293c cxxbridge1$str$ptr + 2770912\nE   14  libsystem_pthread.dylib             0x00000001905282e4 _pthread_start + 136\nE   15  libsystem_pthread.dylib             0x00000001905230fc thread_start + 8"}, "start": 1746613910146, "stop": 1746613930689, "uuid": "3bfd35a4-9c61-44cb-84ed-35e4a01fcbb8", "historyId": "63defa2920c9dcaca3ee64639a60ddde", "testCaseId": "63defa2920c9dcaca3ee64639a60ddde", "fullName": "tests.test_login_page#test_invalid_login", "labels": [{"name": "story", "value": "Invalid login"}, {"name": "feature", "value": "Login"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "XDATA-Christine-Sargsyan.local"}, {"name": "thread", "value": "5072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_page"}]}